### ISSUE TITLE
Cannot Download From User

### ISSUE THREAD

**Issue by BN898** [Kent-Lee/deviantart-scraper#9]
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\Downloads\deviantart-scraper-master\deviantart-scraper-master>$ python main.py artwork
'$' is not recognized as an internal or external command,
operable program or batch file.

D:\Downloads\deviantart-scraper-master\deviantart-scraper-master>python main.py artwork

there are 1 users

download artworks for user TheMightFenek

Traceback (most recent call last):
  File "main.py", line 54, in <module>
    main()
  File "main.py", line 40, in main
    download_users(api, config, args.option)
  File "main.py", line 11, in download_users
    result = api.save_users_artworks(config.users, config.save_dir)
  File "D:\Downloads\deviantart-scraper-master\deviantart-scraper-master\lib\deviantart.py", line 204, in save_users_artworks
    files = self.save_user_artworks(user, dir_path)
  File "D:\Downloads\deviantart-scraper-master\deviantart-scraper-master\lib\deviantart.py", line 180, in save_user_artworks
    files = pool.map(partial(self.save_artwork, dir_path), artworks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\Downloads\deviantart-scraper-master\deviantart-scraper-master\lib\deviantart.py", line 154, in save_artwork
    download_url = self._download_url(artwork)
  File "D:\Downloads\deviantart-scraper-master\deviantart-scraper-master\lib\deviantart.py", line 111, in _download_url
    url = next(a['src'] for a in artwork['files'] if a['type']=='fullview')
KeyError: 'files'

For some reason, I cannot seem to get this to work. Am I missing something in this?

**Comment by mxmlnkn** [comment]
I don't think like you are missing anything. Looks like the deviantart API changed. E.g. the key `files` is now something like `media`. The script is simply outdated it seems.
